sudo: false
language: node_js
node_js:
  - 'node'
  - '5.1'
  - '4.2'
  - '0.12'

before_install: 'gem install scss-lint'
script: 'npm run test-ci'
after_script: 'cat ./coverage/lcov.info | coveralls'
