sudo: false
language: node_js

node_js:
  - 'node'
  - 'iojs'
  - '0.12'
  - '0.10'

before_install:
  - 'gem install scss-lint'

script:
  - 'npm run test-ci'

after_script:
  - 'cat ./coverage/lcov.info | coveralls'
